# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97441b645bd4d47cc298421631629162f1f0631fb1e2446f53cd5398137d1f32ff7b8b3153bd6be212eaf95cf22cc19c128ecf63500e7455d202af299a3ffb4b

test:
  secret_key_base: 663ade808156def252fecc769597a90c13c26b3ea703d83dcd85a07337cb8791c4984e3c5974c4d647763a5298309326b1d81da92dda6261f34c76aed414f9af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
